services:
  - type: web
    name: webhook-server
    env: python
    plan: free
    buildCommand: ""
    startCommand: python server.py
    envVars:
      - key: SECURE_TOKEN
        value: darshit123secure
      - key: TELEGRAM_TOKEN
        value: 7614814256:AAEvxjlgZkLnMHd2GzxK5QBn9tQwpstH28M
      - key: CHAT_ID
        value: 1031264232